server {
    server_name thaliox.io www.thaliox.io;
    root /var/www/thaliox-io;
    index index.html;
    location /_nuxt/ { expires 1y; add_header Cache-Control "public, immutable"; }
    location / { try_files $uri $uri/index.html /index.html; }
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/thaliox.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/thaliox.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server { listen 80; server_name thaliox.io www.thaliox.io; return 301 https://$host$request_uri; }
