server {
    server_name thaliox.dev www.thaliox.dev;
    root /var/www/thaliox-dev;
    index index.html;
    location /_nuxt/ { expires 1y; add_header Cache-Control "public, immutable"; }
    location / { try_files $uri $uri/index.html /index.html; }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/thaliox.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/thaliox.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.thaliox.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = thaliox.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name thaliox.dev www.thaliox.dev;
    return 404; # managed by Certbot




}